# Generated by Django 5.0.6 on 2025-08-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='stop1_surcharge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='stop2_surcharge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='stop1_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_stop1', to='api.location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='stop2_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_stop2', to='api.location'),
        ),
    ]
