# Generated by Django 5.0.6 on 2025-08-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_driver_active_alter_driver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
    ]
