# Generated by Django 5.0.6 on 2025-08-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_vehicle_status_remove_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('unassigned', 'unassigned'), ('assigned', 'assigned'), ('exception', 'exception')], default='unassigned', max_length=20),
        ),
    ]
