# Generated by Django 5.0.6 on 2025-08-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_trip_price_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='exception_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
