# Generated by Django 5.0.6 on 2025-08-22 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_trip_comment_trip_exception_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='invoiced',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='invoiced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
