# Generated by Django 5.0.6 on 2025-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trip_invoiced_trip_invoiced_at_trip_invoiced_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='flight_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='po_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
